xpladev/xpla

cmd/xplad/cmd/root.go

fix: print stdout

---

.github/pull_request_template.md
.github/release-drafter-config.yaml
.github/workflows/go.yaml
.github/workflows/release-drafter.yaml
Makefile
ante/ante_test.go
app/helpers/test_helpers.go

@yoosah @JoowonYun 
- CI is not yet activated
- Adding PR template would be better to describe
- Burden to track changes when writing release note
- CI added
- Added PR template
- Added release drafter - automatically tracks all PR diff and lists

CI & release drafter added

---

ante/ante.go

- Give validators the flexibility to choose gas prices
- Bug deducting fees twice
- follow gas_prices of cosmos
- remove duplicate ante handler

fix: follow gas_prices of cosmos

---

x/reward/abci.go

fix: zero reward

---

app/app.go
app/upgrades/evm/const.go
app/upgrades/evm/types.go
app/upgrades/evm/upgrades.go

@leeyunseon @yoosah 
To add evm, feemarket module as software upgrade
- Params of evm and feemarket must be included in the upgrade `Plan`. 
- Add related items to app.toml

feat: add evm in upgrade module

---

.github/workflows/go.yaml
.github/workflows/integration-test.yaml
.github/workflows/release-drafter.yaml
ante/ante.go
ante/fee.go
integration_test/integration_test.go

@yoosah, @leeyunseon 
Minimize fee difference between cosmos and evm.
Gas-price management for cosmos and evm separately

feat: separate gas_price from evm and cosmos

---

ante/ante.go
ante/fee.go
ante/fee_test.go

@green-blue0 @yoosah @psy2848048 
- When https://github.com/xpladev/xpla/pull/57 is merged, it will go to feature/xatp
- Responding when there are multiple native tokens and XATP

refactor: ante fee

---

app/app.go
app/params/config.go
integration_test/validator1/app.toml
integration_test/validator2/app.toml
integration_test/validator3/app.toml
integration_test/validator4/app.toml
types/cointype.go

@yoosah 
bypass-min-fee-msg-types does not work.

fix: custom config

---

.github/workflows/go.yaml
Dockerfile
go.mod

- https://github.com/cosmos/cosmos-sdk/issues/13373

feat: fixed go version 1.19

---

ante/ante.go
ante/fee.go
ante/fee_test.go
app/params/config.go
cmd/xplad/cmd/root.go
integration_test/validator1/app.toml
integration_test/validator2/app.toml
integration_test/validator3/app.toml
integration_test/validator4/app.toml
x/reward/client/cli/tx.go

@yoosah 
- Doesn't work `bypass-min-fee-msg-types`
- Doesn't use `minimum-gas-prices`
- Upgrade `bypass-min-fee-msg-types` to base config
- Delete `minimum-gas-prices` from app.toml

fix: app.toml configuration

---

go.mod
go.sum

@yoosah @caramis 
https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-002.md

fix: codename cherry

---

app/app.go

@green-blue0 @yoosah 
- cannot `state sync`
- wasm module requires snapshot manager

fix: state sync

---

SECURITY.md

doc: security policy

---

ante/volunteer.go
integration_test/integration_test.go

@leeyunseon 
Volunteer validator stake amount cannot be adjusted
Can self-delegate to volunteer validator

feat: can self-delegate to volunteer validator

---

ante/volunteer.go

@leeyunseon 
- Error handler does not operate normally due to unexpected simulation when gas auto mode.
- Omit simulation when gas auto

fix: broadcast mode correspondence of volunteer ante

---

go.mod
go.sum

@yoosah 
- Error value with slashes in URL template
- https://github.com/cosmos/ibc-go/blob/v4.5.1/CHANGELOG.md#bug-fixes

fix: ibc-go v4.5.1

---

ante/ante.go
integration_test/init_test.go

@leeyunseon @yoosah 
Exception when using base fee to follow EIP
Processing when using base fee

feat: supports base-fee

---

app/upgrades/volunteer/types.go
app/upgrades/volunteer/upgrades.go

@yoosah @leeyunseon 
Additional work is required to use the base fee.
Specify in the parameter code to be changed

chore: redefined volunteer upgrade

---

app/upgrades/volunteer/upgrades.go

rollback: min gas multiplier

---

go.mod
go.sum

@green-blue0 
Ledger does not support XPLA Chain
Changed the ledger to be available using the cosmos app

fix: ledger

---

app/app.go
app/upgrades/v1_4/upgrades.go

@yoosah @green-blue0 
In the case of a wallet created with the initial BaseAccount, evm contract creation is possible, but the state cannot be changed.
Migrate BaseAccount to EthAccount

fix: migrate BaseAccount -> EthAccount

---

go.mod
go.sum

fix: wasmvm 1.3.1

---

cmd/xplad/cmd/root.go

feat: reindex events

---

go.mod
x/staking/keeper/pool.go
x/staking/keeper/val_state_change.go
x/staking/module.go

@yoosah 
follow up cosmos-sdk47 staking module

fix: updated staking module

---

app/keepers/keepers.go
app/modules.go
docs/proto/proto-docs.md
proto/xpla/reward/v1beta1/tx.proto
tests/integration/testutil/common.go
x/reward/exported/exported.go
x/reward/keeper/genesis.go
x/reward/keeper/grpc_query.go
x/reward/keeper/keeper.go
x/reward/keeper/migrations.go
x/reward/keeper/msg_server.go
x/reward/keeper/params.go
x/reward/migrations/v2/migrate.go
x/reward/module.go
x/reward/types/codec.go
x/reward/types/keys.go
x/reward/types/msg.go
x/reward/types/msg_test.go
x/reward/types/params.go
x/reward/types/params_legacy.go
x/reward/types/tx.pb.go

chore: deprecated params module

---

app/keepers/keepers.go

@green-blue0 
- It can't use ics-721
- align ibcfeekeeper

fix: wasmkeeper's parameter

---

go.mod
go.sum

@yoosah 
Can't unmarshal erc20 type
Rollback erc20 proto path

fix: erc20 proto path

---

go.mod
go.sum

@leeyunseon 
Panic when calling empty trace tx
Add request validation in TraceTx

fix: validation Msg in QueryTraceTxRequest

---

app/encoding.go
app/upgrades/v1_5/upgrades.go

feat: migrate VestingAccount to EthAccount

---

docs/proto/proto-docs.md
proto/xpla/reward/v1beta1/tx.proto
x/reward/client/cli/tx.go
x/reward/keeper/keeper.go
x/reward/keeper/msg_server.go
x/reward/types/codec.go
x/reward/types/msg.go
x/reward/types/msg_test.go
x/reward/types/tx.pb.go

@leeyunseon 
How to fill the reward pool

feat: add to fund reward pool

---

app/keepers/keepers.go

feat: set MaxMetadataLen for proposals longer

---

.github/workflows/integration-test.yaml
go.mod
go.sum

https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-004.md

fix: wasmvm v1.5.4

---

app/keepers/keepers.go
app/upgrades/v1_5/upgrades.go
go.mod
go.sum

@yoosah 
https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-005.md

Fix: cwa 2024 005

---

app/keepers/keepers.go
app/modules.go
go.mod
x/auth/keeper/account.go
x/auth/keeper/account_test.go
x/auth/keeper/grpc_query.go
x/auth/keeper/keeper.go
x/auth/module.go
x/auth/types/keys.go

@yoosah 
To use 32 byte address of cosmwasm in evm
Redefine xplaauth and add collections that map 32byte and 20byte to the auth module.

fix: auth query

---

app/keepers/keepers.go
app/modules.go
go.mod
tests/e2e/entrypoint_master.sh
tests/e2e/init_test.go
tests/e2e/integration_test.go
tests/e2e/util_test.go
tests/e2e/wallet_cosmos_test.go
tests/e2e/wallet_evm_test.go
tests/integration/bank/bank_test.go
tests/integration/testutil/common.go
x/bank/keeper/erc20.go
x/bank/keeper/evm_keeper.go
x/bank/keeper/grpc_query.go
x/bank/keeper/keeper.go
x/bank/keeper/msg_server.go
x/bank/module.go
x/bank/types/denom.go
x/bank/types/denom_test.go
x/bank/types/erc20.go
x/bank/types/errors.go
x/bank/types/expected_keepers.go
x/reward/types/msg.go

@yoosah 
It is difficult to transfer tokens such as ERC20 in the Cosmos ecosystem.
Support erc20 transfer in bank module

feat: xplabank module

---

app/app.go
app/upgrades/v1_8/const.go
app/upgrades/v1_8/upgrades.go

apply v1_8 software upgrade code

---

app/keepers/keepers.go
precompile/auth/IAuth.abi
precompile/auth/IAuth.sol
precompile/auth/auth.go
precompile/auth/const.go
precompile/auth/expected_keepers.go
precompile/precompiles.go
tests/e2e/integration_test.go
tests/e2e/util_test.go

- @yoosah 
- @JoowonYun 
- There's data loss in address conversion between Cosmwasm <> EVM
- If Cosmwasm contract address is needed in EVM contract call, there's no interface to retrieve
- Added Cosmwasm address getter interface by EVM address

Implemented some simple auth query methods

---

.github/workflows/docker-publish.yaml

ci: docker build

---

Dockerfile

@nowooj @yoosah 
- Docker build fails due to `minalloc` build error
- Fixed its version that buils properly

fix: pointed specific branch for mimalloc

---

.github/workflows/integration-test.yaml

- @yoosah @nowooj 
- If any commit is appened to the PR that is already opened, CI will not run and the developer should close and reopene ths PR
- Added `synchronize` filter, and it will trigger CI to every PR update
- [] Add related test cases?

CI will run in every fix commit

---

.github/CODEOWNERS

chore: code owner

---

x/bank/keeper/cw20_keeper.go
x/bank/keeper/erc20_keeper.go
x/bank/keeper/keeper.go

@yoosah 
xerc20 and xcw20 cannot check the event
Add events to xerc20 and xcw20 denominator

fix: bank events
